name = "slack-5ch"
main = "src/index.ts"
compatibility_date = "2023-08-07"

[durable_objects]
bindings = [
  { name = "ID_COUNTER", class_name = "IDCounter" }
]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "post_messages"
database_id = "insert_your_d1_database_1d"

[[migrations]]
tag = "v1"
new_classes = ["IDCounter"]