name = "slack-5ch"
main = "src/index.ts"
compatibility_date = "2023-08-07"

[durable_objects]
bindings = [
  { name = "ID_COUNTER", class_name = "IDCounter" }
]

[[migrations]]
tag = "v1"
new_classes = ["IDCounter"]